services:
  query-engine-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - query-engine-network
    volumes:
      - indexer_csv_csv_data:/app/csv_data # Mount the shared volume

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - query-engine-api
    networks:
      - query-engine-network

volumes:
  indexer_csv_csv_data:
    external: true # Shared volume reference

networks:
  query-engine-network:
    driver: bridge
